datasource:
  db:
    development:
    username: ""
    password: ""
    url: "jdbc:h2:./hexlet"
    production:
      username: app
      password: password
      url: jdbc:postgresql://localhost:5432/app

ebean:
  db:
    ddl:
      generate: true
      run: true
      seedSql: seed.sql
